-- Truncate existing data if you want to start fresh (OPTIONAL - comment out if you want to keep existing data)
-- TRUNCATE TABLE room_name_suggestions;

-- MORNING SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('morning', 'Morning Food Hangout'),
('morning', 'Breakfast Brigade'),
('morning', 'Rise & Dine'),
('morning', 'Morning Flavor Club'),
('morning', 'Dawn Delights'),
('morning', 'Early Bird Eats'),
('morning', 'Sunrise Snackers'),
('morning', 'AM Appetite'),
('morning', 'Morning Mouthfuls'),
('morning', 'Brunch Bunch'),
('morning', 'Breakfast Bonanza'),
('morning', 'Morning Food Council'),
('morning', 'Waffle House Party'),
('morning', 'Breakfast Brainstorm'),
('morning', 'Coffee & Food Chat');

-- LUNCH SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('lunch', 'Lunch League'),
('lunch', 'Midday Munch'),
('lunch', 'Noon Nosh Group'),
('lunch', 'Lunch Break Bunch'),
('lunch', 'Midday Feast Finders'),
('lunch', 'Lunch Hour Heroes'),
('lunch', 'Daytime Dining Crew'),
('lunch', 'Midday Menu Explorers'),
('lunch', 'Lunch Decision Committee'),
('lunch', 'Quick Bite Collective'),
('lunch', 'Lunch Special Seekers'),
('lunch', 'Midday Meal Masters'),
('lunch', 'Sandwich Summit'),
('lunch', 'Lunch & Learn'),
('lunch', 'Power Lunch Planners');

-- AFTERNOON SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('afternoon', 'Afternoon Appetites'),
('afternoon', 'Tea Time Treats'),
('afternoon', 'Post-Lunch Planners'),
('afternoon', 'Afternoon Flavor Session'),
('afternoon', 'Snack Attack Squad'),
('afternoon', 'Mid-Day Munchies'),
('afternoon', 'Afternoon Palate Club'),
('afternoon', 'Pre-Dinner Planners'),
('afternoon', 'Afternoon Nibbles'),
('afternoon', 'Coffee Break Foodies'),
('afternoon', 'Afternoon Culinary Club'),
('afternoon', '3PM Food Fix'),
('afternoon', 'Afternoon Cravings Crew'),
('afternoon', 'Snack Time Social'),
('afternoon', 'Teatime Tastings');

-- EVENING SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('evening', 'Dinner Discovery'),
('evening', 'Evening Epicureans'),
('evening', 'Twilight Tastings'),
('evening', 'Night Nosh Collective'),
('evening', 'Prime Time Palates'),
('evening', 'Supper Society'),
('evening', 'Evening Eatery Explorers'),
('evening', 'Nightfall Nibbles'),
('evening', 'Dinner Decision Makers'),
('evening', 'Evening Food Forum'),
('evening', 'Dinner Destination'),
('evening', 'Nighttime Nutrition'),
('evening', 'Sunset Supper Club'),
('evening', 'Dinner Table Talk'),
('evening', 'Evening Edibles');

-- LATE NIGHT SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('latenight', 'Midnight Munchers'),
('latenight', 'After Hours Appetites'),
('latenight', 'Night Owl Nosh'),
('latenight', 'Late Plate Club'),
('latenight', 'Moonlight Menu'),
('latenight', 'Nightcap Nourishment'),
('latenight', 'Late Night Bites Brigade'),
('latenight', 'Owl Hours Eatery'),
('latenight', 'Midnight Snack Society'),
('latenight', 'Late Night Cravings'),
('latenight', 'After-Hours Eats'),
('latenight', 'Nighttime Nibbles'),
('latenight', 'Insomnia Bites'),
('latenight', 'Late Night Food Quest'),
('latenight', 'Midnight Menu Masters');

-- WEEKEND SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('weekend', 'Weekend Food Wanderers'),
('weekend', 'Saturday Sustenance'),
('weekend', 'Sunday Meal Society'),
('weekend', 'Weekend Warriors of Food'),
('weekend', 'Off-Duty Dining Club'),
('weekend', 'Weekend Taste Expedition'),
('weekend', 'Lazy Day Lunchers'),
('weekend', 'Weekend Food Retreat'),
('weekend', 'Saturday Night Specials'),
('weekend', 'Sunday Brunch Bunch'),
('weekend', 'Weekend Food Festival'),
('weekend', 'Saturday Kitchen Collective'),
('weekend', 'Sunday Dinner Circle'),
('weekend', 'Weekend Food Adventure'),
('weekend', 'Relaxed Dining Weekend');

-- OCCASION SUGGESTIONS
INSERT INTO room_name_suggestions (category, text) VALUES
('occasion', 'Birthday Bites Planning'),
('occasion', 'Celebration Feast Finders'),
('occasion', 'Holiday Meal Makers'),
('occasion', 'Special Occasion Eats'),
('occasion', 'Anniversary Dinner Planners'),
('occasion', 'Promotion Party Food'),
('occasion', 'Graduation Grub Group'),
('occasion', 'Reunion Refreshments'),
('occasion', 'Success Celebration Supper'),
('occasion', 'Event Eats Committee'),
('occasion', 'Party Food Planners'),
('occasion', 'Festive Food Forum'),
('occasion', 'Special Event Dining'),
('occasion', 'Celebration Cuisine'),
('occasion', 'Holiday Food Hangout');

-- COOKING MODE SUGGESTIONS
INSERT INTO room_name_suggestions (category, text, food_mode) VALUES
('cooking', 'Cooking Session', 'cooking'),
('cooking', 'Home Chef Gathering', 'cooking'),
('cooking', 'Kitchen Collective', 'cooking'),
('cooking', 'Recipe Roundup', 'cooking'),
('cooking', 'Culinary Workshop', 'cooking'),
('cooking', 'Let''s Cook Something', 'cooking'),
('cooking', 'Kitchen Party', 'cooking'),
('cooking', 'Recipe Exchange Group', 'cooking'),
('cooking', 'Home Cooking Club', 'cooking'),
('cooking', 'Foodie Chef Circle', 'cooking'),
('cooking', 'Meal Prep Party', 'cooking'),
('cooking', 'Spatula Social', 'cooking'),
('cooking', 'Recipe Roulette', 'cooking'), 
('cooking', 'Pan Pals', 'cooking'),
('cooking', 'Kitchen Confidential', 'cooking'),
('cooking', 'Home Chef Collective', 'cooking'),
('cooking', 'Cutting Board Club', 'cooking'),
('cooking', 'Apron Adventures', 'cooking'),
('cooking', 'Mise en Place Meetup', 'cooking'),
('cooking', 'From Scratch Squad', 'cooking'),
('cooking', 'Chef''s Table at Home', 'cooking'),
('cooking', 'Homemade Haven', 'cooking'),
('cooking', 'Kitchen Experiments', 'cooking'),
('cooking', 'Cooking Companions', 'cooking'),
('cooking', 'Taste Test Kitchen', 'cooking');

-- DINING OUT MODE SUGGESTIONS
INSERT INTO room_name_suggestions (category, text, food_mode) VALUES
('dining-out', 'Restaurant Hunt', 'dining-out'),
('dining-out', 'Dining Adventure', 'dining-out'),
('dining-out', 'Food Explorer Group', 'dining-out'),
('dining-out', 'Restaurant Roundtable', 'dining-out'),
('dining-out', 'Dining Decision Squad', 'dining-out'),
('dining-out', 'Foodie Outing', 'dining-out'),
('dining-out', 'Restaurant Tour', 'dining-out'),
('dining-out', 'Taste Test Team', 'dining-out'),
('dining-out', 'Restaurant Scouts', 'dining-out'),
('dining-out', 'Fine Dining Circle', 'dining-out'),
('dining-out', 'Local Eats Explorers', 'dining-out'),
('dining-out', 'Restaurant Ratings Club', 'dining-out'),
('dining-out', 'Table Hoppers', 'dining-out'),
('dining-out', 'Menu Masters', 'dining-out'),
('dining-out', 'Reservation Required', 'dining-out'),
('dining-out', 'Check, Please!', 'dining-out'),
('dining-out', 'Food Critics Club', 'dining-out'),
('dining-out', 'Restaurant Reconnaissance', 'dining-out'),
('dining-out', 'Dining Detectives', 'dining-out'),
('dining-out', 'Eatery Explorers', 'dining-out'),
('dining-out', 'Culinary Quest Team', 'dining-out'),
('dining-out', 'Restaurant Roulette', 'dining-out'),
('dining-out', 'Bistro Browsers', 'dining-out'),
('dining-out', 'Takeout Team', 'dining-out'),
('dining-out', 'Dining Destinations', 'dining-out');

-- BOTH COOKING AND DINING MODE SUGGESTIONS
INSERT INTO room_name_suggestions (category, text, food_mode) VALUES
('both', 'Cook & Dine Experience', 'both'),
('both', 'Kitchen to Table Journey', 'both'),
('both', 'Food Adventure', 'both'),
('both', 'Full Food Experience', 'both'),
('both', 'Cook or Dine Decision', 'both'),
('both', 'Food Journey Collective', 'both'),
('both', 'Food Gathering', 'both'),
('both', 'Complete Food Experience', 'both'),
('both', 'Food Lovers Unite', 'both'),
('both', 'Cooking or Takeout Group', 'both'),
('both', 'Food Decision Makers', 'both'),
('both', 'Eat In or Out Club', 'both'),
('both', 'Fork in the Road', 'both'),
('both', 'Cook or Book Collective', 'both'),
('both', 'Pan or Plan Squad', 'both'),
('both', 'Recipe or Reservation', 'both'),
('both', 'Home or Out Hangout', 'both'),
('both', 'Kitchen/Table Debate', 'both'),
('both', 'Make It or Order It', 'both'),
('both', 'Culinary Choose Your Own Adventure', 'both'),
('both', 'Cooking-Dining Deciders', 'both'),
('both', 'Whisk or Waiter', 'both'),
('both', 'Home Cook or Restaurant Book', 'both'),
('both', 'All Food Options Group', 'both'),
('both', 'Flexible Foodies', 'both');

-- GENERAL SUGGESTIONS (neutral/fallback)
INSERT INTO room_name_suggestions (category, text) VALUES
('general', 'Food Group Chat'),
('general', 'Dinner Decisions'),
('general', 'Lunch Planners'),
('general', 'Foodie Friends'),
('general', 'Meal Planning Committee'),
('general', 'Tasty Times'),
('general', 'Food Adventure Group'),
('general', 'Dining Decisions'),
('general', 'Flavor Explorers'),
('general', 'Food Gang'),
('general', 'Cuisine Collective'),
('general', 'Meal Meet-up'),
('general', 'Food Enthusiasts'),
('general', 'Dining Deliberations'),
('general', 'Culinary Crew'),
('general', 'Taste Buds United'),
('general', 'Food Discussion Forum'),
('general', 'Meal Mates'),
('general', 'Dining Democracy'),
('general', 'Food Focus Group'),
('general', 'Culinary Compass'),
('general', 'The Food Table'),
('general', 'Foodie Finders'),
('general', 'Taste & Talk'),
('general', 'Meal Mission'); 